language: node_js
node_js:
- '4.2'
- '5.1'
before_install:
- npm install -g gulp
script:
- npm install
- gulp
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  on:
    tags: true
    repo: Brightspace/passport-brightspace-auth
  api_key:
    secure: SRdwLeSt7iFpi3ItPoFdvnph+EtDIogIBNeJu7OtuXBw2icWmGg+umuRzMKa5qjk0UBWVjsyj/CqTm9iQWfRIxBIqad5fajmzz3f64CZbbDz2I9lxcj8tRvZxsquFGedxQvVBKNVyesbVS197CYfrg3YiKto6lDyYRGMdWdH/V4cBKzuHrVLNGThGjpa4etnXPt7MKAZOw0eTCzw6XEn8I9Lyio1xe2ar0o0SoFHuLyhUUrbTvwgTOSDFfTRe4PZ0XNiWFHxUq6vinIm5/h+LtDYIwC37Fxvaei7mgMr0qzLDupdrqTnfZGgrGZWJfnXiNdzU2hQ1S2G7rf74S1Aw1teVwnsIImL1w/o0vnCXtZLRIfi2Pune1eQcwzo871N5NjlQBu4FcrouFK68vusOmEHDe4XbGe353yq7iOnEHCn2Y0legMkxauoi5xM6HFkBUGB38HmWv21sdH1TlAF+cHHeNc93WqJd5M1TLp2SDRaRjsgK6KrSutDAcYEu2uwRYTPVY963tM/EEvYS1ivAl6VyHqR6WSlEE2J0SKfKo/ZRC7uVZbpgdwEdXcrVCTkOIAKb728+sxZKlCNQPMKyLPZMJklB7N1/hYlXAIwj+wwfGmX3JKhdE5tDELlQCduLnh5g0mTgClxgHbHBzFz6K3Sn/nP8ZFDmoMRUTZEUQg=
