language: node_js
node_js:
  - '4.2'
  - '5.1'
before_install:
  - npm install -g gulp
script:
  - npm install
  - gulp
deploy:
  provider: script
  on:
    tags: true
    repo: Brightspace/passport-brightspace-auth
  script: echo "npm credentials were revoked on 2018-07-12. We regenerated many
    credentials, but this repository had no changes in at least 18 months and
    was skipped. Reconfigure npm deployments. -omsmith"; exit 1
